# Apple 服务
DOMAIN-SUFFIX,apple.com,大厂-苹果
DOMAIN-SUFFIX,icloud.com,大厂-苹果
DOMAIN-SUFFIX,mzstatic.com,大厂-苹果
DOMAIN-SUFFIX,testflight.apple.com,大厂-苹果
DOMAIN-SUFFIX,developer.apple.com,大厂-苹果
DOMAIN-SUFFIX,appstoreconnect.apple.com,大厂-苹果
DOMAIN-SUFFIX,cdn-apple.com,大厂-苹果
DOMAIN-SUFFIX,apple-dns.net,大厂-苹果
DOMAIN-SUFFIX,apple.cn,大厂-苹果
