# 金融与高吞吐IO
# 金融支付
DOMAIN-KEYWORD,bank,日常-金融支付
DOMAIN-KEYWORD,pay,日常-金融支付
DOMAIN-SUFFIX,alipay.com,日常-金融支付
DOMAIN-SUFFIX,wechatpay.com,日常-金融支付
DOMAIN-SUFFIX,unionpay.com,日常-金融支付
DOMAIN-SUFFIX,hsbc.com,日常-金融支付
DOMAIN-SUFFIX,hsbc.co.uk,日常-金融支付
DOMAIN-SUFFIX,hsbc.com.hk,日常-金融支付
DOMAIN-SUFFIX,capitalone.com,日常-金融支付
DOMAIN-SUFFIX,chase.com,日常-金融支付
DOMAIN-SUFFIX,jpmorgan.com,日常-金融支付
DOMAIN-SUFFIX,citibank.com,日常-金融支付
DOMAIN-SUFFIX,bankofamerica.com,日常-金融支付
DOMAIN-SUFFIX,wellsfargo.com,日常-金融支付
DOMAIN-SUFFIX,discover.com,日常-金融支付
DOMAIN-SUFFIX,americanexpress.com,日常-金融支付
DOMAIN-SUFFIX,interactivebrokers.com,日常-金融支付
DOMAIN-SUFFIX,ibkr.com,日常-金融支付
DOMAIN-SUFFIX,schwab.com,日常-金融支付
DOMAIN-SUFFIX,fidelity.com,日常-金融支付
DOMAIN-SUFFIX,paypal.com,日常-金融支付
DOMAIN-SUFFIX,stripe.com,日常-金融支付
DOMAIN-SUFFIX,wise.com,日常-金融支付
DOMAIN-SUFFIX,revolut.com,日常-金融支付
DOMAIN-SUFFIX,n26.com,日常-金融支付
DOMAIN-SUFFIX,monzo.com,日常-金融支付
DOMAIN-SUFFIX,robinhood.com,日常-金融支付
DOMAIN-SUFFIX,webull.com,日常-金融支付

# 下载
DOMAIN-KEYWORD,aria2,流量-下载
DOMAIN-KEYWORD,xunlei,流量-下载
DOMAIN-KEYWORD,tracker,流量-下载
DOMAIN-KEYWORD,torrent,流量-下载
DOMAIN-SUFFIX,debian.org,流量-下载
DOMAIN-SUFFIX,ubuntu.com,流量-下载
DOMAIN-SUFFIX,archlinux.org,流量-下载
DOMAIN-SUFFIX,kernel.org,流量-下载

# 上传
DOMAIN-SUFFIX,drive.google.com,流量-上传
DOMAIN-SUFFIX,docs.google.com,流量-上传
DOMAIN-SUFFIX,storage.googleapis.com,流量-上传
DOMAIN-SUFFIX,dropbox.com,流量-上传
DOMAIN-SUFFIX,box.com,流量-上传
DOMAIN-SUFFIX,r2.cloudflarestorage.com,流量-上传
DOMAIN-SUFFIX,s3.amazonaws.com,流量-上传
