# GitHub / GitLab
DOMAIN-SUFFIX,github.com,工作-GITHUB
DOMAIN-SUFFIX,githubusercontent.com,工作-GITHUB
DOMAIN-SUFFIX,githubassets.com,工作-GITHUB
DOMAIN-SUFFIX,github.io,工作-GITHUB
DOMAIN-SUFFIX,github.dev,工作-GITHUB
DOMAIN-SUFFIX,ghcr.io,工作-GITHUB
DOMAIN-SUFFIX,gist.github.com,工作-GITHUB
DOMAIN-SUFFIX,raw.githubusercontent.com,工作-GITHUB
DOMAIN-SUFFIX,release-assets.githubusercontent.com,工作-GITHUB
DOMAIN-SUFFIX,codeload.github.com,工作-GITHUB
DOMAIN-SUFFIX,codespaces.githubusercontent.com,工作-GITHUB
DOMAIN-SUFFIX,objects.githubusercontent.com,工作-GITHUB
DOMAIN-SUFFIX,objects-origin.githubusercontent.com,工作-GITHUB
DOMAIN-SUFFIX,avatars.githubusercontent.com,工作-GITHUB
DOMAIN-SUFFIX,githubstatus.com,工作-GITHUB
DOMAIN-SUFFIX,gitlab.com,工作-GITLAB
DOMAIN-SUFFIX,gitlab.io,工作-GITLAB
