# Microsoft
DOMAIN-SUFFIX,microsoft.com,大厂-微软
DOMAIN-SUFFIX,microsoftonline.com,大厂-微软
DOMAIN-SUFFIX,microsoftonline-p.com,大厂-微软
DOMAIN-SUFFIX,office.com,大厂-微软
DOMAIN-SUFFIX,office365.com,大厂-微软
DOMAIN-SUFFIX,microsoft365.com,大厂-微软
DOMAIN-SUFFIX,live.com,大厂-微软
DOMAIN-SUFFIX,outlook.com,大厂-微软
DOMAIN-SUFFIX,hotmail.com,大厂-微软
DOMAIN-SUFFIX,sharepoint.com,大厂-微软
DOMAIN-SUFFIX,onedrive.com,大厂-微软
DOMAIN-SUFFIX,teams.microsoft.com,大厂-微软
DOMAIN-SUFFIX,graph.microsoft.com,大厂-微软
DOMAIN-SUFFIX,login.live.com,大厂-微软
DOMAIN-SUFFIX,azure.com,大厂-微软
DOMAIN-SUFFIX,windows.net,大厂-微软
DOMAIN-SUFFIX,msauth.net,大厂-微软
DOMAIN-SUFFIX,msftauth.net,大厂-微软
DOMAIN-SUFFIX,bing.com,大厂-微软
DOMAIN-SUFFIX,copilot.microsoft.com,大厂-微软
DOMAIN-SUFFIX,dev.azure.com,大厂-微软
DOMAIN-SUFFIX,visualstudio.com,大厂-微软
DOMAIN-SUFFIX,azureedge.net,大厂-微软
DOMAIN-SUFFIX,officeapps.live.com,大厂-微软
