# P1: 基础工具（DNS 与测速）
DOMAIN-SUFFIX,cloudflare-dns.com,日常-DNS解析
DOMAIN-SUFFIX,one.one.one.one,日常-DNS解析
DOMAIN-SUFFIX,dns.google,日常-DNS解析
DOMAIN-SUFFIX,quad9.net,日常-DNS解析
DOMAIN-SUFFIX,speedtest.net,日常-测速
DOMAIN-SUFFIX,fast.com,日常-测速
DOMAIN-SUFFIX,speed.cloudflare.com,日常-测速
