# 流媒体
DOMAIN-SUFFIX,youtube.com,视频-YOUTUBE
DOMAIN-SUFFIX,youtu.be,视频-YOUTUBE
DOMAIN-SUFFIX,youtubei.googleapis.com,视频-YOUTUBE
DOMAIN-SUFFIX,youtube.googleapis.com,视频-YOUTUBE
DOMAIN-SUFFIX,googlevideo.com,视频-YOUTUBE
DOMAIN-SUFFIX,ytimg.com,视频-YOUTUBE
DOMAIN-SUFFIX,yt3.ggpht.com,视频-YOUTUBE
DOMAIN-SUFFIX,youtubeembeddedplayer.googleapis.com,视频-YOUTUBE
DOMAIN-SUFFIX,youtubeeducation.com,视频-YOUTUBE
DOMAIN-SUFFIX,youtubekids.com,视频-YOUTUBE
DOMAIN-SUFFIX,music.youtube.com,视频-YOUTUBE
DOMAIN-SUFFIX,studio.youtube.com,视频-YOUTUBE
DOMAIN-SUFFIX,m.youtube.com,视频-YOUTUBE
DOMAIN-SUFFIX,gvt1.com,视频-YOUTUBE
DOMAIN-SUFFIX,gvt2.com,视频-YOUTUBE
DOMAIN-SUFFIX,gvt3.com,视频-YOUTUBE
DOMAIN-SUFFIX,netflix.com,视频-海外媒体
DOMAIN-SUFFIX,nflxvideo.net,视频-海外媒体
DOMAIN-SUFFIX,nflximg.net,视频-海外媒体
DOMAIN-SUFFIX,disneyplus.com,视频-海外媒体
DOMAIN-SUFFIX,max.com,视频-海外媒体
DOMAIN-SUFFIX,hulu.com,视频-海外媒体
DOMAIN-SUFFIX,primevideo.com,视频-海外媒体
DOMAIN-SUFFIX,spotify.com,视频-海外媒体
DOMAIN-SUFFIX,scdn.co,视频-海外媒体
DOMAIN-SUFFIX,twitch.tv,视频-海外媒体
DOMAIN-SUFFIX,paramountplus.com,视频-海外媒体
DOMAIN-SUFFIX,peacocktv.com,视频-海外媒体
DOMAIN-SUFFIX,crunchyroll.com,视频-海外媒体
GEOIP,NETFLIX,视频-海外媒体
DOMAIN-SUFFIX,steampowered.com,娱乐-游戏
DOMAIN-SUFFIX,steamcommunity.com,娱乐-游戏
DOMAIN-SUFFIX,epicgames.com,娱乐-游戏
DOMAIN-SUFFIX,battle.net,娱乐-游戏
DOMAIN-SUFFIX,blizzard.com,娱乐-游戏
DOMAIN-SUFFIX,ea.com,娱乐-游戏
DOMAIN-SUFFIX,ubisoft.com,娱乐-游戏
DOMAIN-SUFFIX,xboxlive.com,娱乐-游戏
DOMAIN-SUFFIX,playstation.net,娱乐-游戏
DOMAIN-SUFFIX,playstation.com,娱乐-游戏
