# Telegram
DOMAIN-SUFFIX,telegram.org,社交-TELEGRAM
DOMAIN-SUFFIX,t.me,社交-TELEGRAM
DOMAIN-SUFFIX,telegram.me,社交-TELEGRAM
DOMAIN-SUFFIX,telegra.ph,社交-TELEGRAM
IP-CIDR,91.108.0.0/16,社交-TELEGRAM
IP-CIDR,149.154.0.0/16,社交-TELEGRAM
GEOIP,TELEGRAM,社交-TELEGRAM
